### ISSUE TITLE
Set up versions of documentation for mainnet and testnet

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium.github.io#100]
**Task description**

We will need two versions starting with the mainnet.

The testnet4 version will be removed since the testnet is going down, and a new version will need to be added.

I propose that the versions are `mainnet` and `testnet` going forward. The default one should be mainnet once that is operational.

**Comment by limemloh** [comment]
Currently, the plan starting from release of Mainnet, will be to have a `mainnet` branch for the current documentation for Mainnet and use `main` for development of future releases.
Meaning improvements of the mainnet documentation should be merged into both `mainnet` and `main` (if still relevant).

We can use tags on `main` for testnet releases.
