### ISSUE TITLE
Add attribute schemas to developer documentation.

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium.github.io#1001]
**Task description**

Attributes in identity objects are meant to follow certain schemas for encoding. 

These schemas should be documented on the developer documentation. The current list is in a google sheet https://docs.google.com/spreadsheets/d/1CxpFvtAoUcylHQyeBtRBaRt1zsibtpmQOVsk7bsHPGA/edit#gid=0

**Comment by limemloh** [comment]
Closing this since another issue with more detail has been added here https://github.com/Concordium/concordium.github.io/issues/1015
