### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by erasmus** [Concordium/concordium.github.io#1013]
Both links [here](https://github.com/Concordium/concordium.github.io/blob/b96725cc31a922e4d83cb28b09739ae05ea1a156/source/mainnet/net/guides/create-proofs.rst?plain=1#L192) lead to services that are down.

```
You can choose whether you want to use the hosted Concordium verifier for `Mainnet <https://web3id-verifier.mainnet.concordium.software/v0/verify>`__ or `Testnet <https://web3id-verifier.testnet.concordium.com/v0/verify>`__, or whether you want to create your own verifier tool. Note that if you use the hosted verifier then you trust Concordium when verifying proofs.
```

![Screenshot 2024-05-10 at 16 58 07](https://uploads.linear.app/430cc2b6-6b19-45f6-b7f0-6a0093e10c15/e17adbc3-21ff-46e1-b185-49be47130ff5/bacf244c-4ed7-4117-ace9-bad5353aafe4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQzMGNjMmI2LTZiMTktNDVmNi1iN2YwLTZhMDA5M2UxMGMxNS9lMTdhZGJjMy0yMWZmLTQ2ZTEtYjE4NS00OWJlNDcxMzBmZjUvYmFjZjI0NGMtNGVkNy00MTE3LWFjZTktYmFkNTM1M2FhZmU0IiwiaWF0IjoxNzE1MzUzNjA4LCJleHAiOjMzMjg1OTEzNjA4fQ.HA4cY4Q8TtrMEUZEKQHWUomi7GzrYYdUCBynbWigwpc "=841x")

**Comment by DOBEN** [comment]
These are not URLs meant to be opened in a browser.


These are API endpoints that expects a JSON body as described here:

https://github.com/Concordium/concordium-web3id/tree/main/services/web3id-verifier

**Comment by erasmus** [comment]
Clearly, I don't know how to read a manual. Let's close this guy and never speak of it again 😅
