### ISSUE TITLE
Make a Concordium 404 page - paused

### ISSUE THREAD

**Issue by limemloh** [Concordium/concordium.github.io#134]
**Task description**

We should have a 404 page, instead of the default shown by Github Pages.

**Comment by LotteKh** [comment]
@jens-concordium please review the pull request to see if this can be finished.

**Comment by abizjak** [comment]
@dg-concordium This is on the R3 release project board, but it is marked as on-hold here?

Can you either remove it from the R3 board, or explain what should be done with this?

**Comment by dg-concordium** [comment]
@limemloh and @jens-concordium  I am going to take this up and finish it so our 404 page looks nice. But I was wondering if it was possible to add a script on the page that creates an issue in github to tell me where the user was trying to go when the 404 happened. Or even just send a mail.

**Comment by limemloh** [comment]
We believe can use google analytics for tracking this

**Comment by dg-concordium** [comment]
PR 483 merged to solve this.
