### ISSUE TITLE
Contact page for AR and IDP - Paused

### ISSUE THREAD

**Issue by LotteKh** [Concordium/concordium.github.io#171]
Contact page for authorities

**Sub-tasks**
- [ ] How to contact AR
- [ ] How to contact IDP
- [ ] subtask 3

*Add label for component and priority.*

**Comment by dg-concordium** [comment]
@jens-concordium This is nearly a year old. Is it still needed?

**Comment by abizjak** [comment]
Yes, at least the links we have recorded on the chain for "contact information" for ARs should lead to some page.
