### ISSUE TITLE
Difference between accounts made after a certain date

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium.github.io#194]
**Task description**

After [Android issue 17](https://github.com/Concordium/concordium-reference-wallet-android/issues/17) and [iOS issue 23](https://github.com/Concordium/concordium-reference-wallet-ios/issues/23) have been implemented and released, new accounts will have their randomness saved in the database. Practically this means no new features yet, as the option to use the saved randomness to reveal more attributes on accounts will be implemented later.

However, the change will mean that if a user exports accounts with saved randomness, they cannot import it in a version of the mobile wallet that does not support saved randomness. So if they have an export containing accounts with their randomness saved, the user will need an updated version of the app to import them.

**Comment by abizjak** [comment]
Depending on the export format it might just be that the randomness is not imported, but the import still works.

The export file is JSON, which should handle redundant, unrecognized fields.

**Comment by jens-concordium** [comment]
Alright, then let's wait documenting this until we are certain how it's handled, and know what problems it might cause.

In case the import can succeed without importing the randomness, I guess we should consider documenting that the randomness could potentially be lost? If it's exported from a new wallet app, imported in an older version without support for saved randomness, and then exported again from the older app. Probably an unlikely scenario, though.

**Comment by LotteKh** [comment]
@jens-concordium please update status of this issue.

**Comment by jens-concordium** [comment]
Still on pause.

**Comment by dg-concordium** [comment]
@jens-concordium Is this still on pause?

**Comment by jens-concordium** [comment]
@dg-concordium, yes. It's still on pause. The chain still doesn't support making any changes as far as I know, and we may have to reconsider what to do about this, once we get the recovery phrase implemented.

**Comment by dg-concordium** [comment]
@jens-concordium Is this still relevant?

**Comment by jens-concordium** [comment]
@dg-concordium Nope, we can close it.
