### ISSUE TITLE
Expand documentation of error codes for smart contracts

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium.github.io#202]
**Task description**

There is bare-bones documentation of error codes in https://developer.concordium.software/en/mainnet/smart-contracts/guides/custom-errors.html

What is missing is listing of hard-coded error codes assigned to ParseError, (), NewContractNameError and LogError.

**Comment by dg-concordium** [comment]
@abizjak  Do we have descriptions of these hardcoded error codes somewhere?

**Comment by abizjak** [comment]
It's this list
Variant | Error code
-- | --
() | i32::MIN + 1 (-2147483647)
ParseError | i32::MIN + 2 (-2147483646)
LogError::Full | i32::MIN + 3 (-2147483645)
LogError::Malformed | i32::MIN + 4 (-2147483644)
NewContractNameError:://! MissingInitPrefix | i32::MIN + 5 (-2147483643)
NewContractNameError::TooLong | i32::MIN + 6 (-2147483642)
NewContractNameError::ContainsDot | i32::MIN + 9 (-2147483639)
NewContractNameError::InvalidCharacters | i32::MIN + 10 (-2147483638)
NewReceiveNameError::MissingDotSeparator | i32::MIN + 7 (-2147483641)
NewReceiveNameError::TooLong | i32::MIN + 8 (-2147483640)
NewReceiveNameError::InvalidCharacters | i32::MIN + 11 (-2147483637)
NotPayableError | i32::MIN + 12 (-2147483636)
