### ISSUE TITLE
Add description for editable account and identity names

### ISSUE THREAD

**Issue by orhoj** [Concordium/concordium.github.io#204]
**Task description**

In the fall release of the desktop wallet it will be possible to edit the names of accounts and identities. This must be described in the documentation. It has to be described how to edit the names, and any description of the account overview has to be updated as the account name is now also featured on the right-hand side of the screen.

**Comment by dg-concordium** [comment]
@orhoj - What do you mean when you say, "...the account name is now also featured on the right-hand side of the screen."
