### ISSUE TITLE
"License notices" and "Terms and conditions" moved to application menu in the desktop wallet

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium.github.io#214]
**Before 1.2**, “License notices” and “Terms and conditions” documents have been accessible through: Settings > About

**After 1.2** These are accessible through the native application menu under Help.

**MacOS**

<img width="991" alt="image" src="https://user-images.githubusercontent.com/828403/128667963-1f67be92-2b96-42ab-9f8c-d4e74c9f7597.png">

**Windows/Linux**

Note: “Alt” key must be pressed to bring up the menu.

<img width="658" alt="image" src="https://user-images.githubusercontent.com/828403/128667976-f8c8c9e4-568f-457a-b896-06e98045df0f.png">

**Comment by LotteKh** [comment]
Closed with DTW settings, terms and cond, links #277
