### ISSUE TITLE
Smart contract naming scheme missing details

### ISSUE THREAD

**Issue by limemloh** [Concordium/concordium.github.io#237]
**Task description**

Some details are missing from the description of the contract function naming scheme such as:

- The function name is limited to 100 bytes.
- The whole function name must be ASCII alphanumeric and punctuation, not just the contract name.

**Comment by dg-concordium** [comment]
@limemloh Hi Emil. I presume that you mean the "Naming a module" section of this topic: https://developer.concordium.software/en/testnet/smart-contracts/guides/deploy-module.html 
Is that correct?

**Comment by limemloh** [comment]
We do have a bit on the naming scheme here:
https://developer.concordium.software/en/testnet/smart-contracts/general/contract-module.html#smart-contract-on-the-chain

But it is still missing the above-mentioned
