### ISSUE TITLE
Add guide on verifying integrity of downloaded files

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium.github.io#259]
It would be helpful for users to have explicit directions as to how to verify downloaded files by using the sha256 checksums listed alongside each download.

I don't know if we want this as a specific guide under installation (or whereever), or as a section on the downloads page, but it's something which is often included in addition to supplying the checksums of files (see "ledger-live" as an example: https://www.ledger.com/ledger-live/lld-signatures)

To produce a checksum of the downloaded file, the user can run:

Linux:
```bash
sha256sum <path-to-downloaded-file>
```

MacOS: 
```bash
shasum -a 256 <path-to-downloaded-file>
```

Windows (powershell): 
```powershell
Get-FileHash <path-to-downloaded-file> -Algorithm SHA256
```

Furthermore, desktop wallet binaries are signed in order to be able to verify that the binary is indeed an official release from Concordium. Steps on how to verify against the produced signature should also be included here.

To verify a downloaded file (\<file-path\> placeholder in code block) using the provided signature, the user will need:
- The signature file (\<signature-file-path\> placeholder in code block)
- The public key matching the private key used to produce the signature (\<pubkey-file-path\> placeholder in code block)

The file can then be verified by running the following in a terminal:
```bash
openssl dgst -sha256 -verify <pubkey-file-path> -signature <signature-file-path> <file-path>
```

**Sub-tasks**

- [ ] Verify by comparing with published checksum (all downloads with published checksum)
- [ ] Verify with published signature (DTW)

**Comment by abizjak** [comment]
On linux there is a standard `sha256sum` utility which should be used since I don't think openssl is installed by default.

**Comment by soerenbf** [comment]
> On linux there is a standard `sha256sum` utility which should be used since I don't think openssl is installed by default.

On the ledger-live verification guide, there are examples of how this is done on all OS's, all without openssl as well, so we can also just go with what they do. I assume, since they show how to use openssl to verify the signature, that this is the most trivial way of doing that.
