### ISSUE TITLE
Update "Run a node on a server" for Testnet

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium.github.io#264]
**Task description**

Right now [this guide](http://developer.concordium.software/en/testnet/net/guides/run-node-ubuntu.html#run-node-ubuntu)
describes how to upgrade a node from 1.0.1 to 1.1.0.

It should probably also describe how to upgrade to 1.1.2 somehow.

**Comment by abizjak** [comment]
This should just be replacing 1.1.0 to 1.1.2. The only reason 1.1.0 appears is that it was the version to be released at the time I wrote the page.

**Comment by abizjak** [comment]
This should just be replacing 1.1.0 to 1.1.2. The only reason 1.1.0 appears is that it was the version to be released at the time I wrote the page.
