### ISSUE TITLE
Document the utility to decrypt mobile wallet export

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium.github.io#298]
**Task description**

The "utils" utility https://github.com/Concordium/concordium-base/blob/main/rust-bins/src/bin/utils.rs is the only way to decrypt the wallet export file that is sometimes needed when integrating with the chain.

We should link to binaries and document how to use.

**Sub-tasks**
- [ ] Add links to download the utility
- [ ] Document how to use

*Add label for component and priority.*

**Comment by dg-concordium** [comment]
@abizjak Can you provide info about how to run and make available for download?

**Comment by abizjak** [comment]
I'll provide links tomorrow, regarding how to run, it is just the following two commands
```
utils encrypt --in input.blah --out output.json
```
where `--in ...` is the file to encrypt, and `--out` is the file where encrypted data will be written.
This will result in the following interaction
```
Enter password to encrypt with: ....
Re-enter password: ....
Writing output to output.json
```

Dually, to decrypt 
```
utils decrypt --in output.json --out decrypted.blah
```
Enter password to decrypt with: 
Writing output to decrypted.blah
```
With `--in ...` being the encryptd file, and `--out` the decryption.

Let me know if this is enough information.

For an introduction about why you need this tool, I would say something along the lines of "Some concordium tools, such as the mobile wallet, sometimes produce encrypted output. These files can be decrypted and inspected using the `utils` tool ..."
