### ISSUE TITLE
New "common" description of backups across wallets

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium.github.io#301]
**Description**

It would be nice to have a "common" guide or description of backups made from the mobile and desktop wallets, including a description of the difference between how keys are handled. 

This guide could then be linked when suggesting to make a backup in the wallets, and it can be sent to people, when they ask why exports from mobile wallet cannot be imported on desktop, and vice versa. 

Suggestions on what to include:
- How keys are handled in mobile wallet, and explain why it is strongly suggested to make a backup, as there is no seed phrase to recover from.
- How keys are handled in desktop wallet, and why it is extremely important to store the seed phrase, while it is also a very good idea to make a backup from the desktop wallet.
- Conclude that import/export across the two cannot be done, because of the above reasons. 
- Underline that if the keys are lost, and if backups are not made or also lost, there is nothing to do.

**Comment by concordium-cl** [comment]
To be added:
- backup from icloud, if enabled, for synchronization to new phone in case of lost/broken phone
- app passcode is needed (initial passcode, even if later face/touchID is enabled)
