### ISSUE TITLE
Update Ledger installation instructions with info about 2.0.0 / 2.1.0

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium.github.io#337]
**Description**

Updating the Ledger's firmware to 2.1.0 will cause the current version of our Ledger software to not work, when trying to install the custom certificate. This problem should be fixed in the coming version of our Ledger software, but it seems like the 2.1.0 firmware is rolling out quite slowly, so it might be a while before everyone has access to it. 

This means that we might need to have both versions of our software available, so people get the version that fits their Ledger firmware version 2.0.0/2.1.0.

This also means, that we need a description of how and why people should get the one version or the other, when setting up their Ledgers. 

These changes will probably affect both the Ledger installation page and the Download page, on both Mainnet and Testnet documentation.

**Comment by concordium-cl** [comment]
@simonkamp also had problems during his firmware upgrade test when installing the new certificate, because the old certificate needed to be uninstalled first. This might be missing in the documentation. @simonkamp, could you provide more context pls?

**Comment by dg-concordium** [comment]
I need information about this to update the documentation, both related to uninstalling the old certificate as well as any decision flow there might be.

**Comment by simonkamp** [comment]
I used to have the concordium app and CA running on my ledger with a previous firmware version.
After updating to the new firmware I and running the loadcertificate script, step 9 of https://developer.concordium.software/en/testnet/net/desktop-wallet/install-ledger-app.html#install-the-custom-certificate-on-windows did not happen.
I then tried just installing the app anyway following https://developer.concordium.software/en/testnet/net/desktop-wallet/install-ledger-app.html#install-the-concordium-ledger-app-on-windows but after confirming it on the ledger device and waiting for a progress bar, the app was not installed. (Or could not be accessed.)
I then on ran ´python3 -m ledgerblue.resetCustomCA --targetId 0x31100004´ on Sørens advice, after which the loadcertificate and install scripts worked as expected.

**Comment by dg-concordium** [comment]
@simonkamp Do you remember which firmware version you had prior to updating?

**Comment by simonkamp** [comment]
No, unfortunately I did not take note of the previous version.

**Comment by dg-concordium** [comment]
@jens-concordium I'm working on the update per your notes, but what Simon experienced doesn't jive with what you wrote.

**Comment by jens-concordium** [comment]
@simonkamp, @dg-concordium 

I'm not sure if the loadcertificate script has to be run after updating the firmware, if the certificate was already loaded pre-update. Running the script again might have messed with the already installed certificate, but I'm not sure. 

It would probably be good to confirm how things work with @shjortConcordium or @orhoj, just to be sure.

**Comment by shjortConcordium** [comment]
The loadCertificate script is not necessary after updating the firmware, only the install script is needed, to reinstall the app.

The problem Simon had, was that the version, which he got from Søren, was signed using a different key, so it needed a different certificate (which is what his new loadCertificate installed).

For normal users, we will have built the new release with the same key as previously, so they should not remove the certificate.
