### ISSUE TITLE
Update node version numbers from 1.1.3 to 3.0.0 in Testnet docs

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium.github.io#356]
**Task description**

V3.0.0 of the node has already been released on Testnet, but the documentation still mentions 1.1.3. We should update the versioning everywhere to reflect the current release as soon as possible.

We should probably confirm if the upgrade process is still the same as well. 

Affected pages:

- [Run a node on a server with Ubuntu](https://developer.concordium.software/en/testnet/net/guides/run-node-ubuntu.html)
- [Run a node with Docker](https://developer.concordium.software/en/testnet/net/guides/run-node.htm)

**Comment by dg-concordium** [comment]
@abizjak Can you confirm that the upgrade process is the same? If not, who? If so, confirm that it is also the same for Mainnet.

**Comment by abizjak** [comment]
The upgrade for the ubuntu package from 1.1.3 to 3.0.0 is the same as the upgrade from 1.1.2 to 1.1.3 (here https://developer.concordium.software/en/testnet/net/guides/run-node-ubuntu.html#upgrade-from-version-1-1-2-to-1-1-3 )

The one for docker is the same.

**Comment by dg-concordium** [comment]
@abizjak One last question: in the section "Changes to node management in 1.1.3", do we have similar information for 3.0.0? Should we keep this section for 1.1.3 in there and add one for 3.0.0 if it is relevant? Or remove it entirely?

**Comment by abizjak** [comment]
There are no changes in node management between 1.1.3 and 3.0.0. There was only a change from 1.0. to 1.1.2.

I think the section for upgrading from 1.0.1 to 1.1.3 should be removed after this upgrade.
