### ISSUE TITLE
Update node version numbers from 1.1.3 to 3.0.0 in Mainnet docs

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium.github.io#357]
**Task description**
V3.0.0 of the node software will soon be released for Mainnet. For this reason we have to update the Mainnet documentation to reflect the new version. 

We should probably confirm if the upgrade process is still the same as well. 

_This should not be merged to Main nor deployed before the new version of the node has been released for Mainnet_.

Affected pages:

- [Run a node on a server with Ubuntu](https://developer.concordium.software/en/mainnet/net/guides/run-node-ubuntu.html)
- [Run a node with Docker](https://developer.concordium.software/en/mainnet/net/guides/run-node.html)

**Comment by dg-concordium** [comment]
Note to myself: Remember to update Downloads with links to 3.0.0 node files.
