### ISSUE TITLE
Add note about minimum baking threshold to documentation

### ISSUE THREAD

**Issue by dg-concordium** [Concordium/concordium.github.io#399]
Per moderator on Discord there needs to be a note about the minimum staking threshold to be a baker. A user got upset that he could not bake with only 30 CCD.

**Comment by dg-concordium** [comment]
Minimum is 14000 ccd.

**Comment by abizjak** [comment]
Note that this is not fixed and may change, so ideally it would not be hardcoded in the documentation as well since that means it's bound to not be updated.

I'd recommend adding a way to check this instead.

**Comment by dg-concordium** [comment]
Yes, please. A way to check would be much better if it is not fixed. A command in Concordium client or something?

**Comment by dg-concordium** [comment]
Opened issue for this to be made: https://github.com/Concordium/concordium-client/issues/111
