### ISSUE TITLE
Extend The PiggyBank Example

### ISSUE THREAD

**Issue by rimbi** [Concordium/concordium.github.io#403]
**Description**

In order to accelerate external developer adoption, we need to extend the PiggyBank smart contract guide such that it becomes a holistic and easy-to-follow getting-started guide which includes instructions for
  - setting up a local testnet node
  - account creation for testnet
  - importing of created account using concordium-client
  - deploying the smart contract to the local testnet node

Thanks to the previous efforts, all this information already exists in the docs but it is scattered and thus could be a source of frustration for the beginners.

**Steps to Reproduce**

**Expected Result**

One single tutorial doc which explains how to develop and deploy a smart contract to a testnet node.

**Actual Result**

**Versions**
- Software Version
- OS
- Browser
- Mobile device, if applicable

**Comment by dg-concordium** [comment]
@rimbi Would you say that the first three bullets in the list are prerequisites for the example? And is it acceptable to insert links to the existing documentation about how to do this, particularly since the node can be created on one of four platforms? Otherwise, this tutorial will have to be split into multiple topics because it will become too long.

**Comment by abizjak** [comment]
We should not be splitting the tutorial. In many other places in the tutorial we have "prerequisites" with links to other sections.

Only a small portion of the tutorial needs  accounts & concordium-client & the node, prerequisites should only be for those parts.

Development and local testing does not need that.

**Comment by dg-concordium** [comment]
@abizjak I would prefer to do links to the other sections and only where necessary. I do not want to split the tutorial. But the expected result listed above left me with questions about what should be in this topic. Therefore I was trying to clarify.
