### ISSUE TITLE
Document how to obtain test "company identities"

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium.github.io#428]
**Task description**

We currently document how to get a company identity on mainnet, but every exchange we are integrating first needs this for testnet as well.

Until now I've sent them instructions individually each time, but it would be good to have a place to link directly.

The process is essentially the same, except
- they need to use testnet configuration files.
[enterprise-identities-dry-run.zip](https://github.com/Concordium/concordium.github.io/files/8196573/enterprise-identities-dry-run.zip)
- they need to send an email to somebody at concordium. Me, Caro or Emil B have handled these requests in the past, but there are instructions (https://github.com/Concordium/concordium-base/blob/main/rust-bins/docs/identity-provider-cli.md ) that anybody that can use command-line tools can follow.

**Comment by abizjak** [comment]
@concordium-cl @smh1001 add if you have an opinion on this.

**Comment by concordium-cl** [comment]
@abizjak, @smh1001: Could they send an email to support@concordium.software? Then the supporter can take the task and/or ask for help.

**Comment by smh1001** [comment]
Why don't we add a "Company Identity Creation" section in the testnet documentation like we have for mainnet? I think it is fine to refer to support, but the supporter should have somewhere to link the company to.

**Comment by concordium-cl** [comment]
Sorry, I wasn't clear. I meant to add it to the documentation. But in the second step above, they need to send us an email. There we could use support.

**Comment by abizjak** [comment]
@smh1001 that is exactly what this task is about. 

@concordium-cl I agree. If the support team has a place where they gather documentation on specific things, then a link to the instructions on how to generate the response could be added there.

**Comment by concordium-cl** [comment]
@mh-concordium has a support document.

**Comment by mh-concordium** [comment]
This is the document we shared in the support-mainnet channel on Slack. It contains some of the generic replies we could use for support.
https://docs.google.com/document/d/1DoXpz_gy1qhUAbkiU7LrY5k2UTPrYEbHrHR90_a72Og/edit

**Comment by dg-concordium** [comment]
Should I instead add this to the document we created for Alexander to give to the exchanges?

**Comment by abizjak** [comment]
I would prefer if that document is published as part of the developer documentation, i.e., here.

**Comment by dg-concordium** [comment]
@abizjak Will that configuration files zip also work for Linux?

**Comment by abizjak** [comment]
Yes, they are just JSON files, so platform independent.
