### ISSUE TITLE
Remove references to "transaction can only be submitted in a 2h window"

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium.github.io#441]
**Description**

In node version 4.0+ the restriction that a transaction can only be submitted in a 2h window is removed due to other verification being done.

If I recall correctly there are some places where which mention this restriction. These should be updated.

**Comment by dg-concordium** [comment]
@abizjak Does this include the references to things like increasing baker stake where we say "the change will take effect after two epochs, which corresponds to two hours"?

**Comment by abizjak** [comment]
No, that is a different mechanism. Any cooldowns are not affected.

It is only when submitting the transaction to the node that there is no more restriction.
