### ISSUE TITLE
Update third party notices

### ISSUE THREAD

**Issue by dg-concordium** [Concordium/concordium.github.io#680]
We're missing a couple of third-party notices:

- [x] RUST:  its trademarks are owned by the Mozilla Foundation
- [x] node.js: © 2018 Node.js Foundation. Node.js is a trademark of Joyent, Inc. and is used with its permission.
- [x] Linux: LINUX FOUNDATION and YOCTO PROJECT are registered trademarks of the Linux Foundation. Linux® is the registered trademark of Linus Torvalds in the U.S. and other countries.
- [x] Debian needs updating: DEBIAN is a registered trademark owned by [Software in the Public Interest, Inc.](http://www.spi-inc.org/corporate/trademarks/) Debian trademark is a registered United States trademark of Software in the Public Interest, Inc., managed by the Debian project.
- [ ] Ledger needs to be capitalized everywhere: LEDGER.

*Add label for component and priority.*

**Comment by abizjak** [comment]
What about ubuntu?

**Comment by dg-concordium** [comment]
> What about ubuntu?

It's already there today. This is just to update some that aren't there and some we already have but who have since changed their brand. https://developer.concordium.software/en/mainnet/net/resources/third-party-notices.html
