### ISSUE TITLE
Remove versions from titles in download section to avoid breaking links

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium.github.io#771]
We currently specify the version of a piece of software in its title on the downloads page:

![image](https://user-images.githubusercontent.com/5469652/223717126-baab7576-b22f-4176-9ae6-540af0fb1ed9.png)

This means that when you want to link directly to e.g. the node distributions, the link includes the version:
```https://developer.concordium.software/en/mainnet/net/installation/downloads.html#concordium-node-distributions-5-1-3```

When we change the version, the link no longer works as expected in that it not longer scrolls to the correct location on the page.

I propose that we remove the version from the title or at least from the link being generated (if that is easily doable).

**Comment by dg-concordium** [comment]
This was an issue that was open when I started: to add the version number to the titles. https://github.com/Concordium/concordium.github.io/issues/299

So I would suggest that management needs to make a decision about whether or not version should be included in titles. @ali-concordium It does not make sense that I am asked to add and remove them. 

@Bargsteen There is also a page of previous node versions containing all older versions. They are "archived" there when we release a new one.

**Comment by Bargsteen** [comment]
As I read it, the issue you referred is not contradictory to my suggestion.

Jakob wanted "The version of the software that we link to in the download page should be present.", which it now is, fx `https://distribution.mainnet.concordium.software/deb/concordium-mainnet-node_5.1.3-0_amd64.deb`.

What I suggest is that the headers on the downloads page don't have a version number, so that I can refer people to `https://developer.concordium.software/en/mainnet/net/installation/downloads.html#concordium-node-distributions` knowing that the link will also work after next node release.

**Comment by dg-concordium** [comment]
I asked Jakob about the issue before I did the work. He said that it wasn't enough to have it in the file name because some users aren't savvy enough to hover over it to see the version. He felt it needed to be more obvious. As a potential compromise, I could move the version from the main heading to the platform heading, e.g. Ubuntu 5.2.4.

**Comment by abizjak** [comment]
> As I read it, the issue you referred is not contradictory to my suggestion.
> 
> Jakob wanted "The version of the software that we link to in the download page should be present.", which it now is, fx `https://distribution.mainnet.concordium.software/deb/concordium-mainnet-node_5.1.3-0_amd64.deb`.

The version was always present in the link, but as @dg-concordium mentioned it is not visible unless it is actually printed on the page.

I think your suggestion is a good one @dg-concordium .
