### ISSUE TITLE
Hosted web2ID proof explorer and documentation

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium.github.io#818]
**Description**

It would be nice to host the [web2ID verifier front end + back end](https://github.com/Concordium/concordium-misc-tools/tree/main/id-verifier) and to add a section/page after the `gallery` tutorial that leads people to that front end. 

Readers should be able to explore how to create various kinds of zero-knowledge proofs to ask questions/information from the identities in the Concordium browser wallet with this hosted front end (e.g. is the user from the EU, is the user above 18, is the identity document not expired).

Readers can explore how the wallet creates such proofs and how they are verified at the backend. The reader should also explore how the wallet reacts if provided with some wrong input (e.g. a proof that cannot be created from the given identities or if the proof statement is wrong "proof that I am older than 70 and at the same time younger than 20").

**Comment by dg-concordium** [comment]
@DOBEN did we ever ask SRE to host this for us?

**Comment by abizjak** [comment]
Since we have a more general one now https://web3id-proof-explorer.testnet.concordium.com/

that covers everything the other one did, does it make sense to have both?

The mobile wallets, if they ever do, are not going to support the ID2.0 formats anyhow, so the web3id one is sufficient for testing those.

**Comment by DOBEN** [comment]
Closing this issue. The currently hosted proof explore `https://web3id-proof-explorer.testnet.concordium.com/` has even more advanced features than the initial version of it. There is also a link to the proof explorer somwhere in the developer documentation.
