### ISSUE TITLE
Update Run local chain for P6

### ISSUE THREAD

**Issue by dg-concordium** [Concordium/concordium.github.io#924]
Run local chain needs to be updated for P6. https://developer.concordium.software/en/mainnet/net/guides/run-local-chain.html

**Comment by dg-concordium** [comment]
The topic should also be updated to use the correct tokenomics language. E.g. validators, no finalization committee, etc.

**Comment by abizjak** [comment]
I'm not sure it's possible to completely remove the finalization committee since you can set up the chain so that not everybody is a finalizer.

**Comment by dg-concordium** [comment]
> I'm not sure it's possible to completely remove the finalization committee since you can set up the chain so that not everybody is a finalizer.

Probably not. If it is possible to write our way out of it, we can. Otherwise not.
