### ISSUE TITLE
"Move an amount to the shielded balance" instructions inaccurate

### ISSUE THREAD

**Issue by eleanor-em** [Concordium/concordium.github.io#93]
Hi there, just a small issue I noticed while going through [https://developers.concordium.com/en/testnet4/testnet/guides/accounts-transactions.html#move-an-amount-to-the-shielded-balance](https://developers.concordium.com/en/testnet4/testnet/guides/accounts-transactions.html#move-an-amount-to-the-shielded-balance): the instructions for moving funds to the shielded balance say

> Start by pressing the Shielded Balance area of the account card.

However, you cannot transfer funds to the shielded balance this way (since at this stage you have zero shielded balance). You must instead select the "normal" balance, and then the rest of the instructions work.

**Comment by abizjak** [comment]
Thank you for the report. This is indeed phrased incorrectly.

**Comment by eleanor-em** [comment]
Thanks for the quick response and fix!
